worker_processes 1;

events {
    worker_connections 1024;
}

http {

    upstream auth_service {
        server 127.0.0.1:8000;
    }

    upstream driver_service {
        server 127.0.0.1:8001;
    }

    upstream ride_service {
        server 127.0.0.1:8002;
    }

    server {
        listen 9000;
        server_name localhost;

        location /auth/ {
            proxy_pass http://auth_service;
        }

        location /riders/ {
            proxy_pass http://auth_service;
        }

        location /drivers/ {
            proxy_pass http://driver_service;
        }

        location /rides/ {
            proxy_pass http://ride_service;
        }
    }
}