worker_processes 1;

events {
    worker_connections 1024;
}

http {

    upstream auth_service {
        server 127.0.0.1:8000;
    }

    upstream driver_service {
        server 127.0.0.1:8001;
    }

    upstream ride_service {
        server 127.0.0.1:8002;
    }

    server {
        listen 9000;
        server_name localhost;

        # Authentication Service
        location /auth/ {
            proxy_pass http://auth_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rider routes are inside Authentication Service
        location /riders/ {
            proxy_pass http://auth_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Driver Service
        location /drivers/ {
            proxy_pass http://driver_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Ride Service
        location /rides/ {
            proxy_pass http://ride_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}